#pragma once

/* Vulkan queue must contain these bitflags */
#define REQUIRED_QUEUE_FAMILY_BITFLAGS (VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT | VK_QUEUE_TRANSFER_BIT)

/* Data buffer memory must adhere to these requirements */ 
#define REQUIRED_DATA_BUFFER_MEMORY_TYPE_BITFLAGS (VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT)

/* Maximun renderer timeout allowed */
#define HEPH_RENDERER_MAX_TIMEOUT 1000000000







#define HEPH_RENDERER_PIPELINE_VIEWPORT_COUNT 1
#define HEPH_RENDERER_VERTEX_INPUT_ATTR_DESC_BINDING_POSITION 0
#define HEPH_RENDERER_VERTEX_INPUT_ATTR_DESC_BINDING_NORMAL 1